spring.application.name=api
# Credenciales y conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/Gimnasio_db
spring.datasource.username=postgres
spring.datasource.password=f.c.barcelona10

# Configuración de Hibernate (ORM)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true