-- Baseline: refleja el esquema real que Hibernate (ddl-auto=update) ya había generado
-- hasta este punto, tanto en producción como en el entorno local. A partir de acá,
-- todo cambio de esquema se hace con una migración nueva (V2, V3, ...), nunca a mano.

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    CONSTRAINT usuarios_rol_check CHECK (rol IN ('ADMIN', 'GERENCIA'))
);

CREATE TABLE clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(50),
    email VARCHAR(150),
    contrasena VARCHAR(255),
    estado VARCHAR(20) NOT NULL DEFAULT 'INACTIVO',
    CONSTRAINT clientes_estado_check CHECK (estado IN ('ACTIVO', 'MOROSO', 'INACTIVO')),
    CONSTRAINT uk_clientes_email UNIQUE (email)
);

CREATE TABLE planes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    duracion INTEGER NOT NULL,
    precio DOUBLE PRECISION NOT NULL
);

CREATE TABLE pagos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_pago DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    monto_abonado DOUBLE PRECISION NOT NULL,
    cliente_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    CONSTRAINT fk_pagos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_pagos_plan FOREIGN KEY (plan_id) REFERENCES planes(id)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti VARCHAR(36) NOT NULL,
    usuario_id INTEGER NOT NULL,
    expiracion TIMESTAMPTZ NOT NULL,
    revocado BOOLEAN NOT NULL,
    CONSTRAINT uk_refresh_tokens_jti UNIQUE (jti),
    CONSTRAINT fk_refresh_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE cliente_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti VARCHAR(36) NOT NULL,
    cliente_id INTEGER NOT NULL,
    expiracion TIMESTAMPTZ NOT NULL,
    revocado BOOLEAN NOT NULL,
    CONSTRAINT uk_cliente_refresh_tokens_jti UNIQUE (jti),
    CONSTRAINT fk_cliente_refresh_tokens_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);
